apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bens-apreendidos-dev

resources:
- ../../base
- config-map.yaml

patches:
- path: patch_deployment.yaml
  target:
    kind: Deployment
    name: bens-apreendidos-frontend
