apiVersion: apps/v1
kind: Deployment
metadata:
  name: bens-apreendidos-frontend
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"bens-apreendidos-frontend:dev", "namespace":"bens-apreendidos-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bens-apreendidos-frontend\")].image"}]'
spec:
  template:
    spec:
      containers:
        - name: bens-apreendidos-frontend
          image: "image-registry.openshift-image-registry.svc:5000/bens-apreendidos-dev/bens-apreendidos-frontend:dev"
