spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//oracle:1521/oracle
    username: base
    password: senha

  jpa:
    properties:
      hibernate:
        '[default_schema]': base

  security:
    sca2-login-get-jwt: https://homsca2.ibama.serpro.gov.br/sca2sessao/api/v2/sessao/login?service=%s&ticket=%s
    sca2-login-redirect: https://homlogin.sso2.ibama.serpro.gov.br/cas/login?service=%s
    sca2-system-url: http://127.0.0.1/base/login
    sca-get-token: https://homlogin.sso2.ibama.serpro.gov.br/sca2sessao/api/v2/sessao/login
    sca-token-validator: https://homsca2.ibama.serpro.gov.br/sca2sessao/api/v2/sessao/validar
    sca-logout: https://homsca2.ibama.serpro.gov.br/sca2sessao/api/v1/sessao/logout
    sca-logout-redirect: https://homlogin.sso2.ibama.serpro.gov.br/cas/logout?service=
